name: geoinquire-efehr
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyterlab
  - notebook
  - requests
  - pyyaml
  - scipy
  - matplotlib
  - numpy
  - cartopy
  - folium
  - pandas
  - pip
